export const programs = [
    { label: 'Accounting', value: 'Accounting' },
    { label: 'Actuarial Science', value: 'Actuarial Science' },
    { label: 'Aerospace Engineering', value: 'Aerospace Engineering' },
    { label: 'African Studies', value: 'African Studies' },
    { label: 'Agriculture', value: 'Agriculture' },
    { label: 'American Studies', value: 'American Studies' },
    { label: 'Anatomy', value: 'Anatomy' },
    { label: 'Anthropology', value: 'Anthropology' },
    { label: 'Applied Linguistics', value: 'Applied Linguistics' },
    { label: 'Applied Mathematics', value: 'Applied Mathematics' },
    { label: 'Archaeology', value: 'Archaeology' },
    { label: 'Architecture', value: 'Architecture' },
    { label: 'Art History', value: 'Art History' },
    { label: 'Asian Studies', value: 'Asian Studies' },
    { label: 'Astrophysics', value: 'Astrophysics' },
    { label: 'Atmospheric Science', value: 'Atmospheric Science' },
    { label: 'Audiology', value: 'Audiology' },
    { label: 'Biochemistry', value: 'Biochemistry' },
    { label: 'Bioengineering', value: 'Bioengineering' },
    { label: 'Biology', value: 'Biology' },
    { label: 'Biomedical Engineering', value: 'Biomedical Engineering' },
    { label: 'Biophysics', value: 'Biophysics' },
    { label: 'Biostatistics', value: 'Biostatistics' },
    { label: 'Business Administration', value: 'Business Administration' },
    { label: 'Chemical Engineering', value: 'Chemical Engineering' },
    { label: 'Chemistry', value: 'Chemistry' },
    { label: 'Chicano Studies', value: 'Chicano Studies' },
    { label: 'Chinese Language and Literature', value: 'Chinese Language and Literature' },
    { label: 'Civil Engineering', value: 'Civil Engineering' },
    { label: 'Classics', value: 'Classics' },
    { label: 'Cognitive Science', value: 'Cognitive Science' },
    { label: 'Communication Studies', value: 'Communication Studies' },
    { label: 'Comparative Literature', value: 'Comparative Literature' },
    { label: 'Computer Science', value: 'Computer Science' },
    { label: 'Conservation Biology', value: 'Conservation Biology' },
    { label: 'Construction Management', value: 'Construction Management' },
    { label: 'Counseling Psychology', value: 'Counseling Psychology' },
    { label: 'Creative Writing', value: 'Creative Writing' },
    { label: 'Criminal Justice', value: 'Criminal Justice' },
    { label: 'Criminology', value: 'Criminology' },
    { label: 'Cultural Studies', value: 'Cultural Studies' },
    { label: 'Dance', value: 'Dance' },
    { label: 'Data Science', value: 'Data Science' },
    { label: 'Dentistry', value: 'Dentistry' },
    { label: 'Doctor of Education (EdD)', value: 'Doctor of Education (EdD)' },
    { label: 'Doctor of Medicine (MD)', value: 'Doctor of Medicine (MD)' },
    { label: 'Doctor of Veterinary Medicine (DVM)', value: 'Doctor of Veterinary Medicine (DVM)' },
    { label: 'Drama', value: 'Drama' },
    { label: 'Earth Sciences', value: 'Earth Sciences' },
    { label: 'East Asian Studies', value: 'East Asian Studies' },
    { label: 'Ecology', value: 'Ecology' },
    { label: 'Economics', value: 'Economics' },
    { label: 'Education', value: 'Education' },
    { label: 'Electrical Engineering', value: 'Electrical Engineering' },
    { label: 'Engineering Science', value: 'Engineering Science' },
    { label: 'English', value: 'English' },
    { label: 'Environmental Engineering', value: 'Environmental Engineering' },
    { label: 'Environmental Science', value: 'Environmental Science' },
    { label: 'Environmental Studies', value: 'Environmental Studies' },
    { label: 'Epidemiology', value: 'Epidemiology' },
    { label: 'Ethnic Studies', value: 'Ethnic Studies' },
    { label: 'European Studies', value: 'European Studies' },
    { label: 'Family and Consumer Science', value: 'Family and Consumer Science' },
    { label: 'Fashion Design', value: 'Fashion Design' },
    { label: 'Film Studies', value: 'Film Studies' },
    { label: 'Finance', value: 'Finance' },
    { label: 'Fine Arts', value: 'Fine Arts' },
    { label: 'Food Science', value: 'Food Science' },
    { label: 'Forensic Science', value: 'Forensic Science' },
    { label: 'Forestry', value: 'Forestry' },
    { label: 'French Language and Literature', value: 'French Language and Literature' },
    { label: 'Gender Studies', value: 'Gender Studies' },
    { label: 'Genetics', value: 'Genetics' },
    { label: 'Geography', value: 'Geography' },
    { label: 'Geology', value: 'Geology' },
    { label: 'German Language and Literature', value: 'German Language and Literature' },
    { label: 'Global Studies', value: 'Global Studies' },
    { label: 'Graphic Design', value: 'Graphic Design' },
    { label: 'Health Administration', value: 'Health Administration' },
    { label: 'Health Sciences', value: 'Health Sciences' },
    { label: 'History', value: 'History' },
    { label: 'Horticulture', value: 'Horticulture' },
    { label: 'Hospitality and Tourism Management', value: 'Hospitality and Tourism Management' },
    { label: 'Human Development and Family Studies', value: 'Human Development and Family Studies' },
    { label: 'Human Resources', value: 'Human Resources' },
    { label: 'Humanities', value: 'Humanities' },
    { label: 'Industrial Design', value: 'Industrial Design' },
    { label: 'Industrial Engineering', value: 'Industrial Engineering' },
    { label: 'Information Science', value: 'Information Science' },
    { label: 'Information Systems', value: 'Information Systems' },
    { label: 'Information Technology', value: 'Information Technology' },
    { label: 'Interdisciplinary Studies',value: 'Interdisciplinary Studies' },
    { label: 'Interior Design', value: 'Interior Design' },
    { label: 'International Business', value: 'International Business' },
    { label: 'International Relations', value: 'International Relations' },
    { label: 'Italian Language and Literature', value: 'Italian Language and Literature' },
    { label: 'Islamic Studies', value: 'Islamic Studies' },
    { label: 'Japanese Language and Literature', value: 'Japanese Language and Literature' },
    { label: 'Journalism', value: 'Journalism' },
    { label: 'Kinesiology', value: 'Kinesiology' },
    { label: 'Landscape Architecture', value: 'Landscape Architecture' },
    { label: 'Latin American Studies', value: 'Latin American Studies' },
    { label: 'Law', value: 'Law' },
    { label: 'Leadership Studies', value: 'Leadership Studies' },
    { label: 'Library Science', value: 'Library Science' },
    { label: 'Linguistics', value: 'Linguistics' },
    { label: 'Logistics', value: 'Logistics' },
    { label: 'Management', value: 'Management' },
    { label: 'Marine Biology', value: 'Marine Biology' },
    { label: 'Marketing', value: 'Marketing' },
    { label: 'Materials Science', value: 'Materials Science' },
    { label: 'Mathematics', value: 'Mathematics' },
    { label: 'Mechanical Engineering', value: 'Mechanical Engineering' },
    { label: 'Media Studies', value: 'Media Studies' },
    { label: 'Medical Technology', value: 'Medical Technology' },
    { label: 'Medicine', value: 'Medicine' },
    { label: 'Medieval Studies', value: 'Medieval Studies' },
    { label: 'Meteorology', value: 'Meteorology' },
    { label: 'Microbiology', value: 'Microbiology' },
    { label: 'Middle Eastern Studies', value: 'Middle Eastern Studies' },
    { label: 'Military Science', value: 'Military Science' },
    { label: 'Modern Languages', value: 'Modern Languages' },
    { label: 'Molecular Biology', value: 'Molecular Biology' },
    { label: 'Music', value: 'Music' },
    { label: 'Nanotechnology', value: 'Nanotechnology' },
    { label: 'Natural Resource Management', value: 'Natural Resource Management' },
    { label: 'Neuroscience', value: 'Neuroscience' },
    { label: 'Nursing', value: 'Nursing' },
    { label: 'Nutrition', value: 'Nutrition' },
    { label: 'Occupational Therapy', value: 'Occupational Therapy' },
    { label: 'Oceanography', value: 'Oceanography' },
    { label: 'Operations Management', value: 'Operations Management' },
    { label: 'Organizational Leadership', value: 'Organizational Leadership' },
    { label: 'Orthotics and Prosthetics', value: 'Orthotics and Prosthetics' },
    { label: 'Osteopathic Medicine', value: 'Osteopathic Medicine' },
    { label: 'Paleontology', value: 'Paleontology' },
    { label: 'Pakistan Studies', value: 'Pakistan Studies' },
    { label: 'Paralegal Studies', value: 'Paralegal Studies' },
    { label: 'Peace and Conflict Studies', value: 'Peace and Conflict Studies' },
    { label: 'Pharmacology', value: 'Pharmacology' },
    { label: 'Philosophy', value: 'Philosophy'},
    { label: 'Photography', value: 'Photography' },
    { label: 'Physical Education', value: 'Physical Education' },
    { label: 'Physical Therapy', value: 'Physical Therapy' },
    { label: 'Physics', value: 'Physics' },
    { label: 'Physiology', value: 'Physiology' },
    { label: 'Plant Science', value: 'Plant Science' },
    { label: 'Political Science', value: 'Political Science' },
    { label: 'Psychology', value: 'Psychology' },
    { label: 'Clinical Psychology', value: 'Clinical Psychology' },
    { label: 'Public Administration', value: 'Public Administration' },
    { label: 'Public Health', value: 'Public Health' },
    { label: 'Public Relations', value: 'Public Relations' },
    { label: 'Publishing', value: 'Publishing' },
    { label: 'Radiation Therapy', value: 'Radiation Therapy' },
    { label: 'Radiography', value: 'Radiography' },
    { label: 'Real Estate', value: 'Real Estate' },
    { label: 'Recreation and Leisure Studies', value: 'Recreation and Leisure Studies' },
    { label: 'Religious Studies', value: 'Religious Studies' },
    { label: 'Respiratory Therapy', value: 'Respiratory Therapy' },
    { label: 'Risk Management and Insurance', value: 'Risk Management and Insurance' },
    { label: 'Robotics', value: 'Robotics' },
    { label: 'Russian Language and Literature', value: 'Russian Language and Literature' },
    { label: 'Social Work', value: 'Social Work' },
    { label: 'Sociology', value: 'Sociology' },
    { label: 'Software Engineering', value: 'Software Engineering' },
    { label: 'Spanish Language and Literature', value: 'Spanish Language and Literature' },
    { label: 'Special Education', value: 'Special Education' },
    { label: 'Speech-Language Pathology', value: 'Speech-Language Pathology' },
    { label: 'Sports Management', value: 'Sports Management' },
    { label: 'Statistics', value: 'Statistics' },
    { label: 'Sustainability Studies', value: 'Sustainability Studies' },
    { label: 'Systems Engineering', value: 'Systems Engineering' },
    { label: 'Technical Communication', value: 'Technical Communication' },
    { label: 'Telecommunications', value: 'Telecommunications' },
    { label: 'Theater', value: 'Theater' },
    { label: 'Tourism and Travel', value: 'Tourism and Travel' },
    { label: 'Toxicology', value: 'Toxicology' },
    { label: 'Transportation', value: 'Transportation' },
    { label: 'Urban Studies and Planning', value: 'Urban Studies and Planning' },
    { label: 'Veterinary Medicine', value: 'Veterinary Medicine' },
    { label: 'Video Game Design', value: 'Video Game Design' },
    { label: 'Visual Arts', value: 'Visual Arts' },
    { label: 'Web Design', value: 'Web Design' },
    { label: 'Women\'s Studies', value: 'Women\'s Studies' },
    { label: 'Writing', value: 'Writing' },
    { label: 'Zoology', value: 'Zoology' }
];